[2023-07-09 20:51:09,950] INFO _log() L224   * Restarting with stat - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:51:13,066] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:51:13] "GET /aplicacao?nome=sap%20Success%20Factor123 HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:52:56,789] WARNING add_aplicacao() L64   Erro ao adicionar a aplica√ß√£o 'SAP Success Factor', Aplica√ß√£o de mesmo nome j√° salvo na base
(IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: aplicacao.sigla')) - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/app.py L64  
[2023-07-09 20:52:56,792] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:52:56] "[31m[1mPOST /aplicacao HTTP/1.1[0m" 409 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:53:13,939] WARNING add_aplicacao() L64   Erro ao adicionar a aplica√ß√£o 'SAP Success Factor', Aplica√ß√£o de mesmo nome j√° salvo na base
(IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: aplicacao.nome')) - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/app.py L64  
[2023-07-09 20:53:13,940] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:53:13] "[31m[1mPOST /aplicacao HTTP/1.1[0m" 409 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:53:20,563] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:53:20] "POST /aplicacao HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:53:45,681] WARNING add_aplicacao() L64   Erro ao adicionar a aplica√ß√£o 'SAP Success Factor1', Aplica√ß√£o de mesmo nome j√° salvo na base
(IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: aplicacao.sigla')) - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/app.py L64  
[2023-07-09 20:53:45,682] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:53:45] "[31m[1mPOST /aplicacao HTTP/1.1[0m" 409 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:53:54,066] WARNING add_aplicacao() L64   Erro ao adicionar a aplica√ß√£o 'SAP Success Factor1', Aplica√ß√£o de mesmo nome j√° salvo na base
(IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: aplicacao.nome')) - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/app.py L64  
[2023-07-09 20:53:54,067] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:53:54] "[31m[1mPOST /aplicacao HTTP/1.1[0m" 409 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:53:58,762] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:53:58] "POST /aplicacao HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:54:33,822] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:54:33] "GET /aplicacoes?page=undefined&per_page=undefined HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:55:43,701] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:55:43] "DELETE /aplicacao?id=20 HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:55:47,939] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:55:47] "GET /aplicacoes?page=undefined&per_page=undefined HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:56:05,642] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:56:05] "GET /aplicacoes HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-09 20:56:33,302] ERROR log_exception() L1449 Exception on /aplicacao [PUT] - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_openapi3/scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/app.py", line 295, in upd_aplicacao
    query = request.json_data
            ^^^^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'json_data'
[2023-07-09 20:56:33,304] INFO _log() L224  127.0.0.1 - - [09/Jul/2023 20:56:33] "[35m[1mPUT /aplicacao?id=1&nome=SAP%20Success%20Factor&sigla=SSF&descricao=SAP%20Success%20Factor&status=AA HTTP/1.1[0m" 500 - - call_trace=/home/leandro/Documentos/Treinamentos/P√≥s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
