[2023-07-02 12:57:51,098] ERROR log_exception() L1449 Exception on /aplicacao [PUT] - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_openapi3/scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/app.py", line 202, in upd_aplicacao
    aplicacao_id        = query.id
                          ^^^^^^^^
AttributeError: 'dict' object has no attribute 'id'
[2023-07-02 12:57:51,104] INFO _log() L224  127.0.0.1 - - [02/Jul/2023 12:57:51] "[35m[1mPUT /aplicacao HTTP/1.1[0m" 500 - - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-02 12:59:56,750] INFO _log() L224   * Detected change in '/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/app.py', reloading - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-02 13:00:05,397] INFO _log() L224  127.0.0.1 - - [02/Jul/2023 13:00:05] "OPTIONS /aplicacao HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-02 13:00:05,403] ERROR log_exception() L1449 Exception on /aplicacao [PUT] - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_openapi3/scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/app.py", line 204, in upd_aplicacao
    aplicacao_id        = query.id
                          ^^^^^^^^
AttributeError: 'dict' object has no attribute 'id'
[2023-07-02 13:00:05,409] INFO _log() L224  127.0.0.1 - - [02/Jul/2023 13:00:05] "[35m[1mPUT /aplicacao HTTP/1.1[0m" 500 - - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-02 13:01:45,026] INFO _log() L224   * Detected change in '/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/app.py', reloading - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-02 13:02:10,096] INFO _log() L224  127.0.0.1 - - [02/Jul/2023 13:02:10] "OPTIONS /aplicacao HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-02 13:02:10,102] ERROR log_exception() L1449 Exception on /aplicacao [PUT] - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_openapi3/scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/app.py", line 205, in upd_aplicacao
    aplicacao_id        = query.id
                          ^^^^^^^^
AttributeError: 'dict' object has no attribute 'id'
[2023-07-02 13:02:10,108] INFO _log() L224  127.0.0.1 - - [02/Jul/2023 13:02:10] "[35m[1mPUT /aplicacao HTTP/1.1[0m" 500 - - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-02 13:02:32,838] INFO _log() L224  127.0.0.1 - - [02/Jul/2023 13:02:32] "GET /aplicacoes HTTP/1.1" 200 - - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
[2023-07-02 13:10:37,700] INFO _log() L224   * Detected change in '/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/app.py', reloading - call_trace=/home/leandro/Documentos/Treinamentos/PÃ³s Engenharia Software/MVP1/myProjects/app_api/env/lib/python3.11/site-packages/werkzeug/_internal.py L224 
